name: gtk_flutter
description: "Get to know Firebase with Flutter"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  go_router: ^13.0.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  provider: ^6.1.1
  firebase_ui_auth: ^1.12.1
  firebase_storage: ^11.6.0
  flutter_native_splash: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter_native_splash:
  color: "#42a5f5"
  image: assets/megumin.jpg
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
    - assets/megumin.jpg
